# PPO RL-Games IsaacLab Baseline Config
# This config mirrors the baselines/ppo/config.yaml but is adapted for RL-Games and IsaacLab

defaults:
  exp_name: isaaclab_test
  wandb_project: "isaaclab-test"
  task: Isaac-Velocity-Flat-Unitree-A1-v0

isaac_velocity_flat_unitree_a1:
  exp_name: "isaac_velocity_flat_unitree_a1_ppo"
  wandb_project: "isaaclab-test"
  task: Isaac-Velocity-Flat-Unitree-A1-v0 