config: !!python/object/apply:types.SimpleNamespace
  state:
    actor_critic: !!python/object/apply:types.SimpleNamespace
      state:
        act: silu
        norm: layer
    anneal_lr: true
    batch_size: 8192
    capture_video: false
    clip_coef: 0.2
    clip_vloss: true
    cuda: true
    encoder: !!python/object/apply:types.SimpleNamespace
      state:
        act: silu
        cnn_blocks: 0
        cnn_depth: 48
        minres: 4
        mlp_layers: 2
        mlp_units: 256
        norm: layer
        output_dim: 512
        resize: bilinear
    ent_coef: 0.05
    env: !!python/object/apply:types.SimpleNamespace
      state:
        atari: !!python/object/apply:types.SimpleNamespace
          state:
            actions: all
            gray: false
            lives: unused
            noops: 0
            repeat: 4
            resize: opencv
            size: !!python/tuple
            - 64
            - 64
            sticky: true
        dmc: !!python/object/apply:types.SimpleNamespace
          state:
            camera: -1
            repeat: 2
            size: !!python/tuple
            - 64
            - 64
        dmlab: !!python/object/apply:types.SimpleNamespace
          state:
            episodic: true
            repeat: 4
            size: !!python/tuple
            - 64
            - 64
        gym: !!python/object/apply:types.SimpleNamespace
          state:
            obs_key: state
        loconav: !!python/object/apply:types.SimpleNamespace
          state:
            camera: -1
            repeat: 2
            size: !!python/tuple
            - 64
            - 64
        minecraft: !!python/object/apply:types.SimpleNamespace
          state:
            break_speed: 100.0
            size: !!python/tuple
            - 64
            - 64
        robopianist: !!python/object/apply:types.SimpleNamespace
          state:
            render_image: true
    eps: 1.0e-05
    eval: !!python/object/apply:types.SimpleNamespace
      state:
        eval_envs: 4
        eval_interval: 100
        num_eval_configs: 4
        num_eval_episodes: 10
        video_log_interval: 1
    eval_keys: !!python/object/apply:types.SimpleNamespace
      state:
        env1: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(neighbors|door|doors_unlocked|position|has_key)\b
        env2: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(neighbors_unprivileged_nokey|door_unprivileged|doors_unlocked|position|has_key)\b
        env3: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(neighbors_unprivileged_nobutton|door|doors_unlocked_unprivileged|position|has_key)\b
        env4: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(neighbors_unprivileged|door_unprivileged|doors_unlocked_unprivileged|position|has_key)\b
        env5: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
        env6: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
        env7: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
        env8: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
    exp_name: tigerdoorkey_ppo
    full_keys: !!python/object/apply:types.SimpleNamespace
      state:
        cnn_keys: ^$
        mlp_keys: \b(neighbors|door|doors_unlocked|position|has_key)\b
    gae_lambda: 0.95
    gamma: 0.99
    keys: !!python/object/apply:types.SimpleNamespace
      state:
        cnn_keys: ^$
        mlp_keys: \b(neighbors|door|doors_unlocked|position|has_key)\b
    learning_rate: 0.0001
    log_interval: 10
    log_keys_video: !!python/tuple
    - image
    max_grad_norm: 0.5
    minibatch_size: 2048
    norm_adv: true
    num_envs: 8
    num_minibatches: 8
    num_steps: 256
    save_model: false
    seed: 3625374807
    target_kl: null
    task: gymnasium_TigerDoorKey-v0
    torch_deterministic: true
    total_timesteps: 150000
    track: true
    update_epochs: 4
    use_wandb: true
    vf_coef: 0.5
    wandb_entity: null
    wandb_project: sensor-dropout
    wandb_project_name: sensor-dropout
num_eval_configs: 4
policies:
  env1: ./policies/ppo/tigerdoorkey/env1/policy_20250630_013130.pt
  env2: ./policies/ppo/tigerdoorkey/env2/policy_20250630_013003.pt
  env3: ./policies/ppo/tigerdoorkey/env3/policy_20250630_012823.pt
  env4: ./policies/ppo/tigerdoorkey/env4/policy_20250630_012701.pt
policy_type: ppo
task: gymnasium_TigerDoorKey-v0
