Isaac-Ant-v0:
  keys:
    base_height: [0, 1]
    base_lin_vel: [1, 4]
    base_ang_vel: [4, 7]
    base_yaw_roll: [7, 9]
    base_angle_to_target: [9, 10]
    base_up_proj: [10, 11]
    base_heading_proj: [11, 12]
    joint_pos_norm: [12, 20]
    joint_vel_rel: [20, 28]
    feet_body_forces: [28, 52]
    last_actions: [52, 60]
  dropout:
    schedule_type: 'constant'
    base_probability: 0.25
  eval: 
    num_eval_episodes: 20

Isaac-Humanoid-v0:
  keys: 
    base_height: [0, 1]
    base_lin_vel: [1, 4]
    base_ang_vel: [4, 7]
    base_yaw_roll: [7, 9]
    base_angle_to_target: [9, 10]
    base_up_proj: [10, 11]
    base_heading_proj: [11, 12]
    joint_pos_norm: [12, 33]
    joint_vel_rel: [33, 54]
    feet_body_forces: [54, 66]
    last_actions: [66, 87]
  dropout:
    schedule_type: 'constant'
    base_probability: 0.25

Isaac-Lift-Cube-Franka-v0:
  keys: 
    joint_pos: [0, 9]
    joint_vel: [9, 18]
    object_position: [18, 21]
    target_object_position: [21, 28]
    last_actions: [28, 36]
  dropout:
    schedule_type: 'constant'
    base_probability: 0.25

Isaac-Repose-Cube-Shadow-Direct-v0:
  keys:
    hand_joint_pos_scaled: [0, 24]
    hand_joint_vel: [24, 48]
    object_pos: [48, 51]
    object_rot: [51, 55]
    object_lin_vel: [55, 58]
    object_ang_vel: [58, 61]
    goal_pos: [61, 64]
    goal_rot: [64, 68]
    rel_obj_goal_rot: [68, 72]
    fingertip_pos: [72, 87]
    fingertip_rot: [87, 107]
    fingertip_vel: [107, 137]
    last_actions: [137, 157]
  dropout:
    schedule_type: 'constant'
    base_probability: 0.25

Isaac-Repose-Cube-Shadow-With-Contact-Sensors-Direct-v0:
  keys:
    hand_joint_pos_scaled: [0, 24]
    hand_joint_vel: [24, 48]
    object_pos: [48, 51]
    object_rot: [51, 55]
    object_lin_vel: [55, 58]
    object_ang_vel: [58, 61]
    goal_pos: [61, 64]
    goal_rot: [64, 68]
    rel_obj_goal_rot: [68, 72]
    fingertip_pos: [72, 87]
    fingertip_rot: [87, 107]
    fingertip_vel: [107, 137]
    last_actions: [137, 157]
  contact_keys:
    robot0_hand_mount:     [157, 160]
    robot0_forearm:        [160, 163]
    robot0_wrist:          [163, 166]
    robot0_palm:           [166, 169]
    robot0_ffknuckle:      [169, 172]
    robot0_ffproximal:     [172, 175]
    robot0_ffmiddle:       [175, 178]
    robot0_ffdistal:       [178, 181]
    robot0_mfknuckle:      [181, 184]
    robot0_mfproximal:     [184, 187]
    robot0_mfmiddle:       [187, 190]
    robot0_mfdistal:       [190, 193]
    robot0_rfknuckle:      [193, 196]
    robot0_rfproximal:     [196, 199]
    robot0_rfmiddle:       [199, 202]
    robot0_rfdistal:       [202, 205]
    robot0_lfmetacarpal:   [205, 208]
    robot0_lfknuckle:      [208, 211]
    robot0_lfproximal:     [211, 214]
    robot0_lfmiddle:       [214, 217]
    robot0_lfdistal:       [217, 220]
    robot0_thbase:         [220, 223]
    robot0_thproximal:     [223, 226]
    robot0_thhub:          [226, 229]
    robot0_thmiddle:       [229, 232]
    robot0_thdistal:       [232, 235]
  dropout:
    schedule_type: 'constant'
    base_probability: 0.25