config: !!python/object/apply:types.SimpleNamespace
  state:
    actor_critic: !!python/object/apply:types.SimpleNamespace
      state:
        act: silu
        norm: layer
    anneal_lr: true
    batch_size: 8192
    capture_video: false
    clip_coef: 0.2
    clip_vloss: true
    cuda: true
    encoder: !!python/object/apply:types.SimpleNamespace
      state:
        act: silu
        cnn_blocks: 0
        cnn_depth: 48
        minres: 4
        mlp_layers: 2
        mlp_units: 256
        norm: layer
        output_dim: 512
        resize: bilinear
    ent_coef: 0.05
    env: !!python/object/apply:types.SimpleNamespace
      state:
        atari: !!python/object/apply:types.SimpleNamespace
          state:
            actions: all
            gray: false
            lives: unused
            noops: 0
            repeat: 4
            resize: opencv
            size: !!python/tuple
            - 64
            - 64
            sticky: true
        dmc: !!python/object/apply:types.SimpleNamespace
          state:
            camera: -1
            repeat: 2
            size: !!python/tuple
            - 64
            - 64
        dmlab: !!python/object/apply:types.SimpleNamespace
          state:
            episodic: true
            repeat: 4
            size: !!python/tuple
            - 64
            - 64
        gym: !!python/object/apply:types.SimpleNamespace
          state:
            obs_key: state
        loconav: !!python/object/apply:types.SimpleNamespace
          state:
            camera: -1
            repeat: 2
            size: !!python/tuple
            - 64
            - 64
        minecraft: !!python/object/apply:types.SimpleNamespace
          state:
            break_speed: 100.0
            size: !!python/tuple
            - 64
            - 64
        robopianist: !!python/object/apply:types.SimpleNamespace
          state:
            render_image: true
    eps: 1.0e-05
    eval: !!python/object/apply:types.SimpleNamespace
      state:
        eval_envs: 4
        eval_interval: 200
        num_eval_configs: 6
        num_eval_episodes: 50
        video_log_interval: 1
    eval_keys: !!python/object/apply:types.SimpleNamespace
      state:
        env1: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position|position|neighbors_3x3|neighbors_5x5)\b
        env2: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position|position|neighbors_3x3)\b
        env3: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position_unprivileged|position|neighbors_3x3)\b
        env4: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position_unprivileged|position|neighbors_3x3|neighbors_5x5)\b
        env5: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position_unprivileged|position|neighbors_3x3_unprivileged)\b
        env6: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: ^$
            mlp_keys: \b(goal_position_unprivileged|position|neighbors_3x3_unprivileged|neighbors_5x5_unprivileged)\b
        env7: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
        env8: !!python/object/apply:types.SimpleNamespace
          state:
            cnn_keys: .*
            mlp_keys: .*
    exp_name: maze_ppo
    full_keys: !!python/object/apply:types.SimpleNamespace
      state:
        cnn_keys: ^$
        mlp_keys: \b(goal_position|position|neighbors_3x3|neighbors_5x5)\b
    gae_lambda: 0.95
    gamma: 0.99
    keys: !!python/object/apply:types.SimpleNamespace
      state:
        cnn_keys: ^$
        mlp_keys: \b(goal_position|position|neighbors_3x3|neighbors_5x5)\b
    learning_rate: 0.0001
    log_interval: 10
    log_keys_video: !!python/tuple
    - image
    max_grad_norm: 0.5
    minibatch_size: 2048
    norm_adv: true
    num_envs: 8
    num_minibatches: 8
    num_steps: 256
    save_model: false
    seed: 3085863972
    target_kl: null
    task: gymnasium_Maze7x7-v0
    torch_deterministic: true
    total_timesteps: 400000
    track: true
    update_epochs: 4
    use_wandb: true
    vf_coef: 0.5
    wandb_entity: null
    wandb_project: sensor-dropout-2
num_eval_configs: 6
policies:
  env1: ./policies/ppo/maze/env1/policy_20250630_152926.pt
  env2: ./policies/ppo/maze/env2/policy_20250630_152142.pt
  env3: ./policies/ppo/maze/env3/policy_20250630_151418.pt
  env4: ./policies/ppo/maze/env4/policy_20250630_150617.pt
  env5: ./policies/ppo/maze/env5/policy_20250630_145730.pt
  env6: ./policies/ppo/maze/env6/policy_20250630_144918.pt
policy_type: ppo
task: gymnasium_Maze7x7-v0
